version: 2

models:
  - name: dim_listings_cleansed
    decription: Cleansed table which contains Airbnb listings.
    columns:
    - name: listing_id
      decription: Primary key for the listing
      tests:
        - unique
        - not_null

    - name: host_id
      decription: The host's id. Refrences the host table.
      tests:
        - not_null
        - relationships:
            to: ref('dim_hosts_cleansed')
            field: host_id

    - name: room_type
      decription: Type of the aparment / room
      tests:
        - accepted_values:
            values: ['Entire home/apt',
                     'Private room',
                     'Shared room',
                     'Hotel room']

    - name: minimum_nights
      description: '{{ doc("dim_listing_cleansed_minimum_nights") }}'
      tests:
        - positive_value